use async_trait::async_trait;
use oxidauth_kernel::{
    error::BoxedError,
    public_keys::create_public_key::*,
    rsa::{Base64KeyPair, KeyPair},
};
use oxidauth_repository::public_keys::insert_public_key::{
    InsertPublicKeyParams,
    InsertPublicKeyQuery,
};

pub struct CreatePublicKeyUseCase<T>
where
    T: InsertPublicKeyQuery,
{
    public_keys: T,
}

impl<T> CreatePublicKeyUseCase<T>
where
    T: InsertPublicKeyQuery,
{
    pub fn new(public_keys: T) -> Self {
        Self { public_keys }
    }
}

#[async_trait]
impl<T> CreatePublicKeyServiceTrait for CreatePublicKeyUseCase<T>
where
    T: InsertPublicKeyQuery,
{
    #[tracing::instrument(name = "CreatePublicKeyUseCase::create_public_key", skip(self))]
    async fn create_public_key(&self, _params: &CreatePublicKey) -> Result<PublicKey, BoxedError> {
        let Base64KeyPair { public, private } = KeyPair::new()?.base64_encode();

        let params = InsertPublicKeyParams {
            id: None,
            public_key: public,
            private_key: private,
        };

        self.public_keys
            .insert_public_key(&params)
            .await
    }
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use base64::prelude::*;
    use chrono::Utc;

    use super::*;

    fn stored_public_key() -> PublicKey {
        PublicKey {
            id: uuid::uuid!("11111111-1111-4111-8111-111111111111"),
            public_key: "not-decoded-on-create".to_owned(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[derive(Default)]
    struct Log {
        inserts: Vec<(Option<uuid::Uuid>, Vec<u8>, Vec<u8>)>,
    }

    type SharedLog = Arc<Mutex<Log>>;

    fn inserts(log: &SharedLog) -> Vec<(Option<uuid::Uuid>, Vec<u8>, Vec<u8>)> {
        log.lock()
            .expect("log")
            .inserts
            .clone()
    }

    struct MockPublicKeys {
        log: SharedLog,
        fail: bool,
    }

    #[async_trait]
    impl InsertPublicKeyQuery for MockPublicKeys {
        async fn insert_public_key(
            &self,
            req: &InsertPublicKeyParams,
        ) -> Result<PublicKey, BoxedError> {
            self.log
                .lock()
                .expect("log")
                .inserts
                .push((req.id, req.public_key.clone(), req.private_key.clone()));

            if self.fail {
                return Err("simulated insert failure".into());
            }

            Ok(stored_public_key())
        }
    }

    fn use_case(log: &SharedLog, fail: bool) -> CreatePublicKeyUseCase<MockPublicKeys> {
        CreatePublicKeyUseCase::new(MockPublicKeys {
            log: log.clone(),
            fail,
        })
    }

    #[tokio::test]
    async fn a_fresh_rsa_keypair_is_generated_and_stored_base64_encoded() {
        let log = Arc::new(Mutex::new(Log::default()));

        let key = use_case(&log, false)
            .create_public_key(&CreatePublicKey)
            .await
            .expect("create succeeds");

        let captured = inserts(&log);
        assert_eq!(captured.len(), 1);
        let (id, public_b64, private_b64) = &captured[0];
        assert_eq!(id, &None, "the id is always generated by the database");

        let public = BASE64_STANDARD
            .decode(public_b64)
            .expect("stored public key is base64");
        let private = BASE64_STANDARD
            .decode(private_b64)
            .expect("stored private key is base64");

        assert!(
            String::from_utf8_lossy(&public).starts_with("-----BEGIN PUBLIC KEY-----"),
            "public material is a base64-encoded SPKI PEM"
        );
        assert!(
            String::from_utf8_lossy(&private).starts_with("-----BEGIN PRIVATE KEY-----"),
            "private material is a base64-encoded PKCS#8 PEM"
        );

        // the repository row is returned verbatim — create does NOT undo
        // the base64 wrapping (only `list_all` decodes for jwks)
        assert_eq!(key.public_key, "not-decoded-on-create");
    }

    #[tokio::test]
    async fn repository_error_surfaces_unmapped() {
        let log = Arc::new(Mutex::new(Log::default()));

        let error = use_case(&log, true)
            .create_public_key(&CreatePublicKey)
            .await
            .expect_err("insert failure propagates");

        assert_eq!(error.to_string(), "simulated insert failure");
        assert_eq!(inserts(&log).len(), 1, "the keypair was still generated");
    }
}
