[package]
name = "oxidauth-postgres"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "postgres storage implementation for oxidauth"
homepage = "https://oxidauth.rs"
repository = "https://github.com/oxidauth/oxidauth"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
chrono = { version = "0.4.23", features = ["serde"] }
serde = "1.0.152"
serde_json = "1.0.93"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "chrono", "json", "time", "macros", "migrate", "postgres", "tls", "uuid"] }
tokio = { version = "1.25.0", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
