[package]
name = "oxidauth-kernel"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "core lib for oxidauth"
homepage = "https://oxidauth.rs"
repository = "https://github.com/oxidauth/oxidauth"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
chrono = "0.4.24"
oxidauth-postgres = { path = "../oxidauth-postgres" }
uuid = "1.3.2"
