services:
  oxidauth-api:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
      args:
        TARGETVERSION: $RUST_DEV_IMAGE_VERSION
        TARGETPLATFORM: $DOCKER_PLATFORM
    command: /bin/bash -c 'watchexec -c -e rs -r cargo run --bin oxidauth-http'
    platform: $DOCKER_PLATFORM
    stdin_open: true
    tty: true
    environment:
      CARGO_TARGET_DIR: /home/rust/shared_target
      VIRTUAL_HOST: api.oxidauth.localhost
    ports:
      - "80"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - "target-vol:/home/rust/shared_target"
      - ".:/home/rust/src/oxidauth:cached"
    networks:
      default:
        aliases:
          - api.oxidauth.localhost

  postgres:
    image: postgres:16.1
    platform: $DOCKER_PLATFORM
    ports:
      - '5434:5432'
    env_file:
      - '.env'
    volumes:
      - 'postgres-data-vol:/var/lib/postgresql/data'
    networks:
      default:
        aliases:
          - postgres.oxidauth.localhost


volumes:
  target-vol:
  postgres-data-vol:
