[package]
name = "oxidauth-repository"
version = "0.2.0"
edition = "2021"

[dependencies]
oxidauth-kernel = { path = "../oxidauth-kernel" }

async-trait = "0.1.69"
chrono = { version = "0.4.26", features = ["serde"] }
serde_json = "1.0.99"
uuid = { version = "1.4.0", features = ["serde", "v4"] }
