apiVersion: v1
kind: Service
metadata:
  name: {{ template "oxidauth.api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oxidauth.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "oxidauth.api.selectorLabels" . | nindent 4 }}