[package]
name = "oxidauth-http"
version = "0.8.0"
edition = "2021"
license = "GPL-3.0"
description = "http lib and server for oxidauth"
homepage = "https://oxidauth.rs"
repository = "https://github.com/oxidauth/oxidauth"
readme = "README.md"

[dependencies]
oxidauth-kernel = { path = "../oxidauth-kernel" }
oxidauth-usecases = { path = "../oxidauth-usecases" }
oxidauth-postgres = { path = "../oxidauth-postgres" }
oxidauth-permission = { path = "../oxidauth-permission" }
provider = { version = "0.1.0", path = "../../xlib/provider" }
telemetry = { version = "0.1.0", path = "../../xlib/telemetry" }

axum = { version = "0.8.8", features = [
    "http1",
    "json",
    "macros",
    "matched-path",
    "original-uri",
    "tower-log",
    "query",
] }
axum-extra = { version = "0.12.5", features = ["typed-header"] }
axum-macros = "0.4.1"
chrono = { version = "0.4.38", features = ["serde"] }
rust_decimal = { version = "1.36.0", features = ["serde"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs", "cors"] }
tracing = "0.1.40"
url = { version = "2.5.2", features = ["serde"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
