[package]
name = "http"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", default-features = false, features = ["http1", "json", "macros", "matched-path", "original-uri", "tower-log", "query"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.122" }
uuid = { version = "1.10", features = ["serde"] }