[package]
name = "oxidauth-http"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "http lib and server for oxidauth"
homepage = "https://oxidauth.rs"
repository = "https://github.com/oxidauth/oxidauth"
readme = "README.md"

[dependencies]
async-trait = "0.1.64"
axum = "0.6.7"
chrono = "0.4.23"
dotenv = "0.15.0"
hyper = "0.14.24"
reqwest = "0.11.14"
serde = "1.0.152"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["full"] }
tower = "0.4.13"
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.16"
uuid = "1.3.0"
