use oxidauth_kernel::totp_secrets::create_totp_secret::CreateTotpSecretResponse;
use oxidauth_repository::totp_secrets::insert_totp_secret::*;
use sqlx::PgConnection;

use super::*;

#[async_trait]
impl InsertTotpSecretQuery for PgTotpSecretRepository {
    #[tracing::instrument(name = "insert_totp_secret_query", skip(self, params))]
    async fn insert_totp_secret(
        &self,
        params: &InsertTotpSecretParams,
    ) -> Result<CreateTotpSecretResponse, BoxedError> {
        let pool = self.db.write_pool();
        let mut conn = pool.acquire().await?;

        insert_totp_secret_query(&mut conn, params).await?;

        let response = CreateTotpSecretResponse { success: true };

        Ok(response)
    }
}

pub async fn insert_totp_secret_query(
    conn: &mut PgConnection,
    params: &InsertTotpSecretParams,
) -> Result<PgTotpSecret, BoxedError> {
    let result = sqlx::query_as::<_, PgTotpSecret>(include_str!("./insert_totp_secret.sql"))
        .bind(params.user_id)
        .bind(&params.secret_key)
        .fetch_one(conn)
        .await?;

    Ok(result)
}

#[cfg(test)]
mod tests {

    use sqlx::PgPool;

    use super::*;
    use crate::{
        Database,
        test_fixtures::{assert_sql_state, seed_user},
    };

    fn repo(pool: &PgPool) -> PgTotpSecretRepository {
        PgTotpSecretRepository::new(Database::from_pool(pool.clone()))
    }

    #[sqlx::test(migrator = "crate::MIGRATOR")]
    async fn it_should_insert_a_totp_secret(pool: PgPool) {
        let user = seed_user(&pool).await;

        let response = repo(&pool)
            .insert_totp_secret(&InsertTotpSecretParams {
                user_id: user,
                secret_key: "JBSWY3DPEHPK3PXP".to_owned(),
            })
            .await
            .expect("insert should succeed");
        assert!(response.success);

        let (id, secret, created): (Uuid, String, DateTime<Utc>) = sqlx::query_as(
            "SELECT id, totp_secret, created_at FROM totp_secrets WHERE user_id = $1",
        )
        .bind(user)
        .fetch_one(&pool)
        .await
        .expect("row must be persisted");
        assert_eq!(secret, "JBSWY3DPEHPK3PXP");
        assert!(!id.is_nil(), "the id is generated by uuid_generate_v4()");
        assert!(created.timestamp() > 0);
    }

    #[sqlx::test(migrator = "crate::MIGRATOR")]
    async fn it_should_allow_duplicate_secrets_per_user(pool: PgPool) {
        // BUG(pinned): the audit expects "duplicate per user" rejection, but the schema
        // has NO unique constraint on totp_secrets.user_id — a second enrollment for
        // the same user is silently accepted and both rows persist.
        let user = seed_user(&pool).await;
        let repo = repo(&pool);
        let params = InsertTotpSecretParams {
            user_id: user,
            secret_key: "JBSWY3DPEHPK3PXP".to_owned(),
        };

        repo.insert_totp_secret(&params)
            .await
            .expect("first enrollment should succeed");
        repo.insert_totp_secret(&params)
            .await
            .expect("second enrollment is accepted — no uniqueness on user_id");

        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM totp_secrets WHERE user_id = $1")
            .bind(user)
            .fetch_one(&pool)
            .await
            .expect("count should run");
        assert_eq!(count, 2);
    }

    #[sqlx::test(migrator = "crate::MIGRATOR")]
    async fn it_should_reject_an_unknown_user(pool: PgPool) {
        let err = repo(&pool)
            .insert_totp_secret(&InsertTotpSecretParams {
                user_id: Uuid::new_v4(),
                secret_key: "JBSWY3DPEHPK3PXP".to_owned(),
            })
            .await
            .expect_err("an unknown user id must violate the users FK");
        assert_sql_state(err, "23503");
    }
}
